### ISSUE TITLE
Mod not working on Steam version of the game

### ISSUE THREAD

**Issue by MonteXMat** [ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog#1]
Hi,

As per the [Steam discussion](https://steamcommunity.com/sharedfiles/filedetails/?id=1532423055&tscn=1638990956), I'm unable to get this to work with the Steam version of the game.

**Comment by ThirteenAG** [comment]
Thanks, let's see if this one works. 
[AlienIsolation.SkipSaveConfirmationDialog.asi.zip](https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/files/7678748/AlienIsolation.SkipSaveConfirmationDialog.asi.zip)

**Comment by ThirteenAG** [comment]
Also perhaps upload an exe, I don't see why it would be different than the one I have, but just to make sure.

**Comment by MonteXMat** [comment]
Still seeing pop-up while saving after replacing the file.
[Link to .exe](https://www.dropbox.com/s/9ebg92lqqh5pw1d/AI.exe?dl=0)

**Comment by ThirteenAG** [comment]
[AlienIsolation.SkipSaveConfirmationDialog.asi.zip](https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/files/7678888/AlienIsolation.SkipSaveConfirmationDialog.asi.zip)

**Comment by MonteXMat** [comment]
For some reason after replacing the file I can't launch the game through the AliasIsolation mod.
It worked alright before replacing.
I've tried all of the files you uploaded with and without the mod just to make sure that it's not causing the issue.

**Comment by MonteXMat** [comment]
Sorry to bother you regarding this, but would I be of any help to you?
Any logs or details I could share to help you out?
I don't want to rush you and I frankly don't have any right to, but I'd just love to find a solution to this.

**Comment by ThirteenAG** [comment]
Yes, stay put, I'll continue investigating this in a couple of days, and I will need your help.

**Comment by ThirteenAG** [comment]
[AlienIsolation.SkipSaveConfirmationDialog.asi.zip](https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/files/7703031/AlienIsolation.SkipSaveConfirmationDialog.asi.zip)
Can you try this version and see if there's a message box appears?

**Comment by MonteXMat** [comment]
Still appears after replacing 😢

**Comment by ThirteenAG** [comment]
What appears? I'm talking about messagebox from windows.
![](https://i.stack.imgur.com/8X5hZ.png)
Like this one.

**Comment by MonteXMat** [comment]
I launch the game as normal, everything loads, I'm at the first save location and as I try to save the overwrite pop-up appears.
I've tried progessing in the game as well and the same thing happens.
There is no errors upon launching the game or during saving.

**Comment by ThirteenAG** [comment]
So yeah, that's the problem. First, launch the game, then alt tab. Open a program called PE Tools, select alien isolation process, click dump full and upload that file here.

**Comment by MonteXMat** [comment]
Done, uploaded [here](https://www.dropbox.com/s/3vgdvwma2jw76zn/Dumped.exe?dl=0).

**Comment by ThirteenAG** [comment]
I don't see anything wrong with the plugin, it seems like asi is not getting loaded at all.
And if I'm right, try installing this plugin and confirm there's no messagebox on startup.
[MessageBox.zip](https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/files/7706166/MessageBox.zip)

**Comment by MonteXMat** [comment]
![image](https://user-images.githubusercontent.com/36119026/145872292-5e106d50-acfe-4dc1-a434-23a4e1e7c458.png)

**Comment by ThirteenAG** [comment]
[AlienIsolation.SkipSaveConfirmationDialog.asi.zip](https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/files/7706359/AlienIsolation.SkipSaveConfirmationDialog.asi.zip)
Ugh, check this one for empty message box, and if it appears, check save dialog in game.

**Comment by MonteXMat** [comment]
No empty box on start & save dialog still showing up in-game.

**Comment by ThirteenAG** [comment]
But it should work. Are you using [latest version](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/Win32-latest/winmm.zip) of asi loader still btw?

**Comment by MonteXMat** [comment]
I'm using the one in the v1.1 mod zip from 2018.
Just replaced with the winmm.zip you posted, still no empty pop-up & save dialog still showing.

**Comment by ThirteenAG** [comment]
Then I'm out of ideas. You said it's working as is with epic's version, so I have no idea why it doesn't with steam, especially because it works for me. 

What about if you create winmm.ini in root dir with this:
```
[GlobalSets]
LoadPlugins=1
LoadFromScriptsOnly=0
DontLoadFromDllMain=0
```

**Comment by MonteXMat** [comment]
Yeah, it is really weird that it works fine with the Epic version of the game.
Created a winmm.ini file in root dir with:

```
[GlobalSets]
LoadPlugins=1
LoadFromScriptsOnly=0
DontLoadFromDllMain=0
```

Still no empty pop-up on start & save dialog showing in-game :c

**Comment by ThirteenAG** [comment]
No idea man. This one shows anything at all?
[AlienIsolation.SkipSaveConfirmationDialog.asi.zip](https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/files/7706710/AlienIsolation.SkipSaveConfirmationDialog.asi.zip)

**Comment by MonteXMat** [comment]
![image](https://user-images.githubusercontent.com/36119026/145882415-45d6a556-a595-431a-b477-2b753c1ce779.png)
![image](https://user-images.githubusercontent.com/36119026/145882431-f814cbea-ae88-40dc-9870-7eb4ead2f717.png)
![image](https://user-images.githubusercontent.com/36119026/145882449-6e4a8eea-4850-4d03-b7e1-2dc965fbcf3f.png)

Got these 3 on start, but overwrite pop-up still shows up during a save.

**Comment by ThirteenAG** [comment]
Well, there should be 4 of those. The one that actually does everything ain't working.
Try to rename winmm.dll to d3d11.dll.

**Comment by MonteXMat** [comment]
Ayyyyyyyyyyyyyyyyyyyyyy it worked! 💯 
No .ini file needed in the root folder. Got an extra pop-up on start.
Thank you so much for your time and effort!

**Comment by ThirteenAG** [comment]
Very weird, but alright. Usually winmm works fine. There's no other option to rename it to, so I'll add a note to the guide and github release.
