### ISSUE TITLE
GOG

### ISSUE THREAD

**Issue by Klemci** [ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog#2]
Just, not works on this version (store).

Thanks.

**Comment by ThirteenAG** [comment]
I don't have that version. If you could send an exe, I'd take a look.

**Comment by Klemci** [comment]
Yes, good thanks:

[GOGExe.zip](https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/files/14217589/GOGExe.zip)

**Comment by ThirteenAG** [comment]
Actually it should work already. Tried 

> If it doesn't work, try to rename winmm.dll to d3d11.dll.

?

**Comment by Klemci** [comment]
Oh, a third one ?.. i just opened an issue on Alias-Isolation updated :

https://github.com/RyanJGray/aliasIsolation/issues/25

Bc i have 3DMigoto that is already d3d11 DLL (perhaps he's the culprist), also,  this AIsolation update needs UASILoader named d3d11 !!!

How will i sort al that out.

**Comment by ThirteenAG** [comment]
Rename the other dll to d3d11Hooked.dll

**Comment by Klemci** [comment]
ALLRight, it's UASILoader btw, perfect, it means i can use newest AIsolation next !!

But it didn't work, so i'll look at 3DM readme to see if he can load third party DLL and how :p 

//

EDIT:
yes, works if 3DMigoto deleted :\ 
But i prefer get rid of oranges glow that just the save prompt...

**Comment by ThirteenAG** [comment]
Actually you need to update asi loader, download https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/Win32-latest/d3d11-Win32.zip, then use that as d3d11.dll, and rename the other dll to d3d11Hooked.dll.

**Comment by Klemci** [comment]
Yes, yes, yes... many thanks.

So:
3DMigoto Hooked DLL, for no orange glow objects (muste have)
+
aliasisolation ASI newer (UASILoader)  (THE muste have)
+
Skip Save Prompt ((UASILoader - too) (good one)

We're done with it !!!
